telethon:
    TELEGRAM_BOT_TOKEN_Infinity2pW3_Bot: 6024638403:AAEfTT8wg7B96pXvrLD73Qc0SPwz6LaqMc8
    TELEGRAM_CHAT_ID_Javis_2p_w3: -1001963906049
    TELEGRAM_CHAT_ID_Javis_2p_w3_Online: -100787641997

    
    
    